/**
 * SP v1 request signing (P3 / PLAN-open-platform §7).
 *
 * Resellers (upstream channel partners) authenticate with a key pair and an
 * Ed25519 signature over a canonical request string, rather than a bearer token.
 * Three headers travel with every call:
 *
 *   - `X-SP-Key-Id`    — public key identifier (selects the Reseller row).
 *   - `X-SP-Timestamp` — Unix seconds; a signed request is only valid inside a
 *                        bounded window, so a captured signature expires.
 *   - `X-SP-Nonce`     — random per request; consumed once so a replayed
 *                        (still-in-window) request is rejected.
 *   - `X-SP-Signature` — base64 Ed25519 over the canonical string below.
 *
 * Canonical string (LF-joined, body hashed so large payloads are not signed
 * verbatim):
 *
 *   <METHOD>\n<path+query>\n<timestamp>\n<nonce>\n<sha256hex(body)>
 *
 * The signing key pair is generated by the operator and stored on the Reseller
 * row; this module is deliberately pure (no DB) so the exact bytes signed by a
 * partner are unit-testable.
 */
import { createHash, createPrivateKey, createPublicKey, sign, verify } from 'node:crypto';

export const SP_HEADERS = {
  keyId: 'x-sp-key-id',
  timestamp: 'x-sp-timestamp',
  nonce: 'x-sp-nonce',
  signature: 'x-sp-signature',
} as const;

/** Replay window: a signature is valid for ±this many seconds from now. */
export const SIGNATURE_WINDOW_SECONDS = 300;

export class SignatureError extends Error {}

/** sha256 hex of a request body (empty string for no body). */
export function bodyDigest(body: string | Uint8Array | undefined): string {
  const bytes = body === undefined ? Buffer.alloc(0) : Buffer.from(body);
  return createHash('sha256').update(bytes).digest('hex');
}

/** Build the canonical string a partner signs for one request. */
export function canonicalRequest(input: {
  method: string;
  /** Path including query string, e.g. `/sp/v1/orders?page=1`. */
  path: string;
  timestamp: string;
  nonce: string;
  bodyDigest: string;
}): string {
  return [
    input.method.toUpperCase(),
    input.path,
    input.timestamp,
    input.nonce,
    input.bodyDigest,
  ].join('\n');
}

/** Sign a canonical string with a PEM Ed25519 private key; returns base64. */
export function signCanonical(canonical: string, privateKeyPem: string): string {
  const key = createPrivateKey(privateKeyPem);
  if (key.asymmetricKeyType !== 'ed25519') {
    throw new SignatureError('签名私钥不是 Ed25519');
  }
  return sign(null, Buffer.from(canonical, 'utf8'), key).toString('base64');
}

/** Verify a base64 Ed25519 signature over a canonical string. */
export function verifyCanonical(
  canonical: string,
  signatureBase64: string,
  publicKeyPem: string,
): boolean {
  try {
    const key = createPublicKey(publicKeyPem);
    if (key.asymmetricKeyType !== 'ed25519') return false;
    const sig = Buffer.from(signatureBase64, 'base64');
    if (sig.length === 0) return false;
    return verify(null, Buffer.from(canonical, 'utf8'), key, sig);
  } catch {
    return false;
  }
}

/** Validate an Ed25519 public key (PEM). */
export function isValidEd25519PublicKey(publicKey: string): boolean {
  try {
    return createPublicKey(publicKey).asymmetricKeyType === 'ed25519';
  } catch {
    return false;
  }
}

/** Validate an Ed25519 private key (PEM). */
export function isValidEd25519PrivateKey(privateKey: string): boolean {
  try {
    return createPrivateKey(privateKey).asymmetricKeyType === 'ed25519';
  } catch {
    return false;
  }
}

export interface SignatureInput {
  method: string;
  path: string;
  timestamp: string;
  nonce: string;
  signature: string;
  body?: string | Uint8Array;
  /** Inject the current time (epoch ms) for deterministic tests. */
  now?: number;
}

export type SignatureResult =
  | { ok: true }
  | { ok: false; reason: 'malformed' | 'expired' | 'invalid' };

/**
 * Verify signature + timestamp window. Nonce replay is checked separately
 * (it needs shared state) by {@link consumeNonce}; this function is pure.
 */
export function verifyRequestSignature(
  input: SignatureInput,
  publicKeyPem: string,
): SignatureResult {
  const { timestamp, signature } = input;
  if (!/^\d{1,20}$/.test(timestamp) || signature.length === 0) {
    return { ok: false, reason: 'malformed' };
  }
  const sentSeconds = Number(timestamp);
  const nowSeconds = Math.floor((input.now ?? Date.now()) / 1000);
  if (Math.abs(nowSeconds - sentSeconds) > SIGNATURE_WINDOW_SECONDS) {
    return { ok: false, reason: 'expired' };
  }
  const canonical = canonicalRequest({
    method: input.method,
    path: input.path,
    timestamp,
    nonce: input.nonce,
    bodyDigest: bodyDigest(input.body),
  });
  return verifyCanonical(canonical, signature, publicKeyPem)
    ? { ok: true }
    : { ok: false, reason: 'invalid' };
}

/** Extract the four SP headers, or null when any is missing. */
export function readSignatureHeaders(headers: Record<string, unknown>): {
  keyId: string;
  timestamp: string;
  nonce: string;
  signature: string;
} | null {
  const pick = (name: string): string | null => {
    const value = headers[name];
    const raw = Array.isArray(value) ? value[0] : value;
    return typeof raw === 'string' && raw.length > 0 ? raw : null;
  };
  const keyId = pick(SP_HEADERS.keyId);
  const timestamp = pick(SP_HEADERS.timestamp);
  const nonce = pick(SP_HEADERS.nonce);
  const signature = pick(SP_HEADERS.signature);
  if (!keyId || !timestamp || !nonce || !signature) return null;
  if (nonce.length > 128) return null;
  return { keyId, timestamp, nonce, signature };
}
