#!/usr/bin/env node
/**
 * Scaffold a new distributable StackPanel plugin.
 *
 * Usage:
 *   pnpm plugin:create <id> [--name "My Plugin"] [--frontend] [--help]
 *
 * <id> must match ^[a-z0-9_-]{1,64}$ and must not collide with built-in or
 * reserved ids (hello/store/ticket/wowid/zjmf-upstream/epay/kernel/default).
 *
 * Generates packages/plugins/<id>/ with a typed backend entry (definePlugin)
 * and, with --frontend, a frontend package discovered by scripts/build-frontend.mjs
 * (packages/plugins/<id>/frontend/package.json). Afterwards the workspace
 * lockfile is refreshed so the new member is linked.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pluginsDir = path.join(root, 'packages', 'plugins');

const RESERVED_IDS = new Set([
  'hello',
  'store',
  'ticket',
  'wowid',
  'zjmf-upstream',
  'epay',
  'kernel',
  'default',
]);
const ID_PATTERN = /^[a-z0-9_-]{1,64}$/;

function usage() {
  console.log(`Usage: pnpm plugin:create <id> [--name "My Plugin"] [--frontend] [--help]

Creates packages/plugins/<id> from the template.

Options:
  --name "Display Name"   Plugin display name (default: title-cased id)
  --frontend              Also scaffold a frontend package (pages, admin page, settings)
  --help                  Show this help
`);
}

const args = process.argv.slice(2);
const positional = [];
const options = { name: undefined, frontend: false };
for (let index = 0; index < args.length; index += 1) {
  const arg = args[index];
  if (arg === '--help' || arg === '-h') {
    usage();
    process.exit(0);
  }
  if (arg === '--name') {
    options.name = args[++index];
    if (!options.name) {
      console.error('--name requires a value.');
      process.exit(1);
    }
    continue;
  }
  if (arg === '--frontend') {
    options.frontend = true;
    continue;
  }
  if (arg.startsWith('-')) {
    console.error(`Unknown option: ${arg}`);
    usage();
    process.exit(1);
  }
  positional.push(arg);
}

const id = positional[0];
if (!id || positional.length > 1) {
  usage();
  process.exit(1);
}
if (!ID_PATTERN.test(id)) {
  console.error(`Invalid plugin id "${id}". Must match ${ID_PATTERN.toString()}.`);
  process.exit(1);
}
if (RESERVED_IDS.has(id)) {
  console.error(`Reserved plugin id "${id}". Pick another id.`);
  process.exit(1);
}

const target = path.join(pluginsDir, id);
if (existsSync(target)) {
  console.error(`Already exists: ${target}`);
  process.exit(1);
}

const name =
  options.name ?? id.replace(/[-_]/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
const packageName = `@stackpanel/plugin-${id}`;
const frontendPackageName = `${packageName}-frontend`;

mkdirSync(path.join(target, 'src'), { recursive: true });
if (options.frontend) {
  mkdirSync(path.join(target, 'frontend', 'src'), { recursive: true });
}

const packageJson = {
  name: packageName,
  version: '0.1.0',
  private: true,
  type: 'module',
  license: 'MIT',
  description: `StackPanel plugin: ${name}.`,
  exports: {
    '.': {
      types: './dist/index.d.ts',
      import: './dist/index.js',
    },
  },
  files: ['dist'],
  scripts: {
    prepare: 'tsc -p tsconfig.build.json',
    build: 'tsc -p tsconfig.build.json',
    typecheck: 'tsc -p tsconfig.json',
  },
  dependencies: {
    '@stackpanel/sdk': 'workspace:*',
  },
  devDependencies: {
    '@types/node': '^22.20.1',
    typescript: '^6.0.3',
  },
};

const src = `import { definePlugin } from '@stackpanel/sdk';
import type { HttpReply, HttpRequest } from '@stackpanel/sdk';

/**
 * ${name} plugin scaffold.
 *
 * Demonstrates:
 * - a public route (GET /${id}/hello)
 * - an admin-only route guarded by a permission declared in the manifest
 * - a role template granting that permission to the ADMIN role
 * - an event listener and lifecycle hooks
 *
 * Extension points (packages/sdk/src/plugin.ts):
 *   provides:  [EXTENSION_POINTS.<name>]  + ctx.registerExtension in onActivate
 *   consumes:  [{ pluginId, extensionPoint }] + ctx.getExtensions in onActivate
 */
async function helloHandler(req: HttpRequest, _reply: HttpReply): Promise<unknown> {
  const who = req.query['who'];
  return {
    message: \`${name} says hello\${typeof who === 'string' && who.length > 0 ? \`, \${who}\` : ''}!\`,
  };
}

async function statusHandler(_req: HttpRequest, _reply: HttpReply): Promise<unknown> {
  return { plugin: '${id}', version: '0.1.0', status: 'ok' };
}

export const ${id.replace(/[^a-zA-Z0-9]/g, '_')}Plugin = definePlugin({
  manifest: {
    id: '${id}',
    name: '${name}',
    version: '0.1.0',
    description: '${name} — plugin generated by pnpm plugin:create.',
    permissions: ['${id}:admin'],
    roleTemplates: [{ role: 'ADMIN', permissions: ['${id}:admin'] }],
    // provides: ['${id}.extensionPoint'],
    // consumes: [{ pluginId: 'hello', extensionPoint: '${id}.extensionPoint', optional: true }],
  },
  routes: [
    { method: 'GET', path: '/${id}/hello', handler: helloHandler },
    {
      method: 'GET',
      path: '/admin/${id}/status',
      handler: statusHandler,
      auth: 'admin',
      permission: '${id}:admin',
    },
  ],
  eventListeners: [
    {
      topic: 'plugin.activated',
      handler: () => {
        // React to platform events (e.g. record audit entries).
      },
    },
  ],
  onRegister: (ctx) => ctx.logger.info('${id}: registered'),
  onActivate: (ctx) => ctx.logger.info('${id}: activated'),
  onDeactivate: (ctx) => ctx.logger.info('${id}: deactivated'),
});

export default ${id.replace(/[^a-zA-Z0-9]/g, '_')}Plugin;
`;

const statusSchema = `const statusSchema = z.object({
  plugin: z.string(),
  version: z.string(),
  status: z.string(),
});`;

// Server entry: public pages, finders and declarative route metadata. Admin
// routes are declared here but their components live in `src/admin.tsx`, which
// is compiled to `dist/admin.js` and resolved on the client by the web app.
const frontendSource = `import type { FinderContext, FrontendPackage } from '@stackpanel/sdk';
import { PageHeader } from '@stackpanel/ui';
import type { ReactElement } from 'react';
import { z } from 'zod';

/** Public page rendered by the web shell under /${id}. */
function ${id.replace(/[^a-zA-Z0-9]/g, '_')}Page(): ReactElement {
  return (
    <main className="w-full space-y-8">
      <PageHeader title="${name}" description="Public page contributed by the ${id} plugin." />
    </main>
  );
}

${statusSchema}

const finders = {
  '${id}.status': async (_input: Record<string, unknown>, ctx: FinderContext) =>
    ctx.api.get('/admin/${id}/status', statusSchema),
};

export const frontend: FrontendPackage = {
  pages: [{ path: '/${id}', component: '${id}/index' }],
  pageComponents: { '${id}/index': ${id.replace(/[^a-zA-Z0-9]/g, '_')}Page },
  finders,
  ui: {
    adminRoutes: [
      {
        path: '/overview',
        component: 'admin/overview',
        permission: '${id}:admin',
        nav: { label: '${name}', group: '插件' },
        data: [{ finder: '${id}.status', as: 'status' }],
      },
    ],
  },
};

// Required: the server registry resolves the frontend package from the default
// export. Without it every page/route of this plugin becomes a silent 404.
export default frontend;
`;

// Client entry (optional but required for interactive admin pages). Any admin
// page referenced by `ui.adminRoutes[].component` must be exported from the
// `adminPages` map here. See the developer guide: frontend / admin-extensions.
const frontendAdminSource = `'use client';

import type { AdminPageComponentProps } from '@stackpanel/sdk';
import { PageHeader } from '@stackpanel/ui';
import type { ReactElement } from 'react';
import { z } from 'zod';

${statusSchema}

/** Admin overview page backed by a finder hitting /admin/${id}/status. */
function ${id.replace(/[^a-zA-Z0-9]/g, '_')}AdminPage(
  props: AdminPageComponentProps,
): ReactElement {
  const status = props.data.status as z.infer<typeof statusSchema> | undefined;
  return (
    <main className="w-full space-y-8">
      <PageHeader title="${name}" description="管理入口。" />
      {status ? (
        <dl className="grid gap-3 rounded-lg border bg-card p-4 text-sm sm:grid-cols-3">
          <div>
            <dt className="text-muted-foreground">版本</dt>
            <dd className="mt-1 font-mono">{status.version}</dd>
          </div>
          <div>
            <dt className="text-muted-foreground">状态</dt>
            <dd className="mt-1">{status.status}</dd>
          </div>
        </dl>
      ) : null}
    </main>
  );
}

// Keys must match the \`component\` values declared in ui.adminRoutes.
export const adminPages = {
  'admin/overview': ${id.replace(/[^a-zA-Z0-9]/g, '_')}AdminPage,
} as const;
`;

const readme = `# ${name} (${id})

${options.frontend ? 'Backend + frontend' : 'Backend-only'} plugin scaffolded by
\`pnpm plugin:create ${id}\`.

## Develop

\`\`\`bash
pnpm install                                # link the new workspace member
pnpm --filter ${packageName} typecheck       # type-check
pnpm --filter ${packageName} build           # compile dist/
pnpm build:frontend                          # build + materialize frontend packages (--frontend only)
pnpm plugin:pack ${id}                       # pack dist-pack/${id}-0.1.0.zip
\`\`\`

## Install the packed plugin

Upload \`dist-pack/${id}-0.1.0.zip\` in the admin Plugins page, or seed it under
\`data/plugins/${id}/\` before boot. Hot install/upgrade/removal is supported —
no restart required.

## Layout

- \`src/index.ts\` — typed \`definePlugin\` entry (manifest, routes, hooks)
- \`frontend/\` — optional frontend package (pages, finder, admin route)
- \`assets/\` — optional static files copied into the packed ZIP

The kernel validates \`apiVersion\` compatibility and rejects source files
(\`.ts\`/\`.tsx\`) inside uploaded archives. Plugins are executable code — treat
uploads as trusted.
`;

const tsconfig = {
  extends: '../../../tsconfig.base.json',
  compilerOptions: { noEmit: true, types: ['node'] },
  include: ['src/**/*.ts'],
};

const tsconfigBuild = {
  extends: '../../../tsconfig.base.json',
  compilerOptions: {
    noEmit: false,
    declaration: true,
    declarationMap: true,
    sourceMap: true,
    outDir: 'dist',
    rootDir: 'src',
    types: ['node'],
  },
  include: ['src/**/*.ts'],
};

const frontendPackageJson = {
  name: frontendPackageName,
  version: '0.1.0',
  private: true,
  type: 'module',
  scripts: {
    build:
      'tsup src/index.tsx --format esm --out-dir dist --platform neutral --clean --external react --external react/jsx-runtime --external @stackpanel/sdk --jsx automatic',
  },
  dependencies: { zod: '^4.4.3' },
  license: 'MIT',
};

function write(relative, content) {
  const file = path.join(target, relative);
  writeFileSync(file, content);
  console.log(`  created ${path.relative(root, file)}`);
}

write('package.json', `${JSON.stringify(packageJson, null, 2)}\n`);
write('tsconfig.json', `${JSON.stringify(tsconfig, null, 2)}\n`);
write('tsconfig.build.json', `${JSON.stringify(tsconfigBuild, null, 2)}\n`);
write('src/index.ts', src);
write('README.md', readme);
if (options.frontend) {
  write('frontend/package.json', `${JSON.stringify(frontendPackageJson, null, 2)}\n`);
  write('frontend/src/index.tsx', frontendSource);
  write('frontend/src/admin.tsx', frontendAdminSource);
}

execFileSync('pnpm', ['prettier', '--write', `packages/plugins/${id}`], {
  cwd: root,
  stdio: 'inherit',
});

console.log(`\nScaffolded packages/plugins/${id}. Refreshing the workspace lockfile…\n`);
execFileSync('pnpm', ['install'], { cwd: root, stdio: 'inherit' });

console.log(`
Next steps:
  pnpm --filter ${packageName} typecheck
  pnpm --filter ${packageName} build
${options.frontend ? `  pnpm build:frontend\n  pnpm plugin:pack ${id}` : `  pnpm plugin:pack ${id}`}
`);
