import 'server-only';

import type { FrontendPackage } from '@stackpanel/sdk';
import { getFrontendPackage } from './frontend-registry';

/**
 * Re-export the generated frontend registry so existing imports continue to work.
 *
 * The registry is generated by `pnpm build:frontend` and contains a static import
 * for every installed frontend package (built-in or third-party). Keeping all
 * imports static guarantees that every package shares the same React instance and
 * avoids runtime `import()` of a file URL, which would load a second copy of
 * React and break hooks.
 */
export { getFrontendPackage, listFrontendPackageIds } from './frontend-registry';

/** @deprecated Use `getFrontendPackage` from `./frontend-registry`. */
export function builtinFrontendModule(
  kind: 'themes' | 'plugins',
  id: string,
): FrontendPackage | null {
  return getFrontendPackage(kind, id);
}
